all:
  children:
    servers:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/lab/ansible_lab_ed25519
        ansible_become: true
      hosts:
        srv1:
          ansible_host: 127.0.0.1
          ansible_port: 2221
        srv2:
          ansible_host: 127.0.0.1
          ansible_port: 2222
        srv3:
          ansible_host: 127.0.0.1
          ansible_port: 2223

    swarm_manager:
      hosts:
        srv1:

    swarm_workers:
      hosts:
        srv1:
        srv2:
        srv3:
